### ISSUE TITLE
invalidate image list cache when changing subscription attributes

### ISSUE THREAD

**Issue by arax** [hepix-virtualisation/vmcatcher#9]
When changing subscription attributes, such as using options
```bash
--imagelist-newimage-accept
```
or
```bash
--imagelist-newimage-subscribe
```
, image list cache should be invalidated.

**Comment by osynge** [comment]
ok thanks this is an important usability bug

**Comment by osynge** [comment]
This is a proposed fix 9c7cb81e71c16a4e6b08db6a555fe266e212b8b0.

It will undergo testing tonight.

**Comment by osynge** [comment]
resolved with 0.6.1 release
